<?php
/*
 *
 * Implements hook_menu().
 *
 */
function amp_menu(){
	$items['admin/config/development/amp'] = array(
		'title' => 'APM',
		'description' => 'AMP Google experimental module',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('amp_admin'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function amp_admin() {
  $form = array();
  $form['amp_routes'] = array(
    '#type' => 'textarea',
    '#title' => t('URLs to include'),
    '#default_value' => variable_get('amp_routes'),
    '#description' => t("Specify all the URLs to include."),
    '#required' => TRUE,
  );
  $form['amp_style_amp_boilerplate'] = array(
    '#type' => 'textarea',
    '#title' => t('Style boilerplate for AMP'),
    '#default_value' => variable_get('amp_style_amp_boilerplate'),
    '#description' => t("Specify style boilerplate for AMP."),
    '#required' => TRUE,
  );
  $form['amp_scripts'] = array(
    '#type' => 'textarea',
    '#title' => t('Scripts for AMP'),
    '#default_value' => variable_get('amp_scripts'),
    '#description' => t("Specify scripts for AMP."),
    '#required' => TRUE,
  );
  $form['amp_custom_style'] = array(
    '#type' => 'textarea',
    '#title' => t('Custom style for AMP'),
    '#default_value' => variable_get('amp_custom_style'),
    '#description' => t("Specify custom style for AMP."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function amp_admin_validate($form, &$form_state){
	//routes for AMP implementation
	$amp_routes = $form_state['values']['amp_routes'];
	$urls_array = explode("\n", $amp_routes);
	$urls_serialized = serialize($urls_array);

	//style boilerplate
	$amp_style_boilerplate = $form_state['values']['amp_style_amp_boilerplate'];
	$style_amp_boilerplate_array = explode("\n", $amp_style_boilerplate);
	$style_amp_boilerplate_serialized = serialize($style_amp_boilerplate_array);

	//scripts for AMP
	$amp_scripts = $form_state['values']['amp_scripts'];
	$amp_scripts_array = explode("\n", $amp_scripts);
	$amp_scripts_serialized = serialize($amp_scripts_array);

	//Custom style form AMP
	$amp_custom_style = $form_state['values']['amp_custom_style'];
	$amp_custom_style_array = explode("\n", $amp_custom_style);
	$amp_custom_style_serialized = serialize($amp_custom_style_array);

	variable_set('amp_routes', $urls_serialized);
	variable_set('amp_style_amp_boilerplate', $style_amp_boilerplate_serialized);
	variable_set('amp_scripts', $amp_scripts_serialized);
	variable_set('amp_custom_style', $amp_custom_style_serialized);
}

/**
 *
 * Implements hook_preprocess_page();
 *
 */
function amp_preprocess(&$variables, $hook){
	module_load_include('inc','amp','amp');
	//validar hook page
	if($hook == 'html'){
		//dpm(validateAmpFunctionality());
	}
}

/**
 *
 * Implements hook_form_alter()
 *
 */
function amp_form_alter(&$form, &$form_state, $form_id){
	//dpm($form);
	//validar que se trata de un formulario
}